# Generated by Django 2.1.3 on 2018-11-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20181105_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
                ('time', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='teachwork',
            name='time',
            field=models.DateField(),
        ),
    ]
