# Generated by Django 2.1.3 on 2018-11-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_auto_20181129_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='people',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
