# Generated by Django 2.1.3 on 2018-11-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_auto_20181129_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='danwei',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='lectureTime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
