# Generated by Django 2.1.3 on 2018-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_auto_20181129_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='peopleIntroduce',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
