# Generated by Django 2.1.3 on 2018-11-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_lecture_peopleintroduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
