# Generated by Django 2.1.3 on 2018-11-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0016_auto_20181129_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='file',
            field=models.FileField(null=True, upload_to='file'),
        ),
    ]
