# Generated by Django 2.1.3 on 2018-11-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_remove_material_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content1', models.TextField(max_length=2000)),
                ('content2', models.TextField(max_length=2000)),
                ('content3', models.TextField(max_length=2000)),
                ('file', models.FileField(null=True, upload_to='file')),
                ('time', models.DateField()),
            ],
        ),
    ]
