# Generated by Django 2.1.3 on 2018-11-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0019_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content1',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content2',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content3',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
    ]
